### ISSUE TITLE
Doesn't work on PHP Files

### ISSUE THREAD

**Issue by gaisho** [proficientdesigners/sublime-text-bs4-snippets#2]
Hello.  Please update the package to work with PHP files as well.

**Comment by proficientdesigners** [comment]
Hi, @vusisindane, actually it'll work inside php tag too, please find the screenshots..

![Screenshot_1](https://user-images.githubusercontent.com/41690645/67300323-676aab00-f50b-11e9-8db5-b350f41e8287.png)

![Screenshot_2](https://user-images.githubusercontent.com/41690645/67300220-430ece80-f50b-11e9-8821-3a788b455788.png)

![Screenshot_8](https://user-images.githubusercontent.com/41690645/68001720-49c7df00-fc8b-11e9-85c7-dbd34ad173ad.jpg)

Which sublime version are you using ?
